# Generated by Django 5.1.6 on 2025-02-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chef", "0001_initial")]

    operations = [migrations.DeleteModel(name="Chef")]
