# Generated by Django 5.1.6 on 2025-02-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chef", "0003_chef")]

    operations = [migrations.DeleteModel(name="Chef")]
